dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
script:
    - flake8
    - mypy pybunpro
    - pytest
    - python setup.py sdist bdist_wheel
    - cd docs
    - make html
    - touch build/html/.nojekyll
    - touch build/html/_static/.nojekyll
    - touch build/html/_sources/.nojekyll
after_success:
  - coveralls
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: docs/build/html
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
